// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oax-models.proto

// Protobuf Java Version: 3.25.1
package top.openadexchange.oax.model.proto;

public final class OaxModelsProto {
  private OaxModelsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code top.openadexchange.oax.model.proto.LogType}
   */
  public enum LogType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GLOBAL = 0;</code>
     */
    GLOBAL(0),
    /**
     * <code>BID_REQ = 1;</code>
     */
    BID_REQ(1),
    /**
     * <code>BID_RSP = 2;</code>
     */
    BID_RSP(2),
    /**
     * <code>DSP_REQ = 3;</code>
     */
    DSP_REQ(3),
    /**
     * <code>DSP_RSP = 4;</code>
     */
    DSP_RSP(4),
    ;

    /**
     * <code>GLOBAL = 0;</code>
     */
    public static final int GLOBAL_VALUE = 0;
    /**
     * <code>BID_REQ = 1;</code>
     */
    public static final int BID_REQ_VALUE = 1;
    /**
     * <code>BID_RSP = 2;</code>
     */
    public static final int BID_RSP_VALUE = 2;
    /**
     * <code>DSP_REQ = 3;</code>
     */
    public static final int DSP_REQ_VALUE = 3;
    /**
     * <code>DSP_RSP = 4;</code>
     */
    public static final int DSP_RSP_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LogType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LogType forNumber(int value) {
      switch (value) {
        case 0: return GLOBAL;
        case 1: return BID_REQ;
        case 2: return BID_RSP;
        case 3: return DSP_REQ;
        case 4: return DSP_RSP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LogType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LogType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogType>() {
            public LogType findValueByNumber(int number) {
              return LogType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.openadexchange.oax.model.proto.OaxModelsProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final LogType[] VALUES = values();

    public static LogType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LogType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.openadexchange.oax.model.proto.LogType)
  }

  public interface LogSamplingConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.openadexchange.oax.model.proto.LogSamplingConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 主键ID
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <pre>
     * 主键ID
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
     * </pre>
     *
     * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
     * @return Whether the logType field is set.
     */
    boolean hasLogType();
    /**
     * <pre>
     * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
     * </pre>
     *
     * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
     * @return The logType.
     */
    top.openadexchange.oax.model.proto.OaxModelsProto.LogType getLogType();

    /**
     * <pre>
     * 媒体ID
     * </pre>
     *
     * <code>optional int32 media_id = 3;</code>
     * @return Whether the mediaId field is set.
     */
    boolean hasMediaId();
    /**
     * <pre>
     * 媒体ID
     * </pre>
     *
     * <code>optional int32 media_id = 3;</code>
     * @return The mediaId.
     */
    int getMediaId();

    /**
     * <pre>
     * DSP平台ID
     * </pre>
     *
     * <code>optional int32 dsp_id = 4;</code>
     * @return Whether the dspId field is set.
     */
    boolean hasDspId();
    /**
     * <pre>
     * DSP平台ID
     * </pre>
     *
     * <code>optional int32 dsp_id = 4;</code>
     * @return The dspId.
     */
    int getDspId();

    /**
     * <pre>
     * 媒体广告位ID
     * </pre>
     *
     * <code>optional int32 ad_slot_id = 5;</code>
     * @return Whether the adSlotId field is set.
     */
    boolean hasAdSlotId();
    /**
     * <pre>
     * 媒体广告位ID
     * </pre>
     *
     * <code>optional int32 ad_slot_id = 5;</code>
     * @return The adSlotId.
     */
    int getAdSlotId();

    /**
     * <pre>
     *媒体广告位编码
     * </pre>
     *
     * <code>optional string ad_slot_code = 10;</code>
     * @return Whether the adSlotCode field is set.
     */
    boolean hasAdSlotCode();
    /**
     * <pre>
     *媒体广告位编码
     * </pre>
     *
     * <code>optional string ad_slot_code = 10;</code>
     * @return The adSlotCode.
     */
    java.lang.String getAdSlotCode();
    /**
     * <pre>
     *媒体广告位编码
     * </pre>
     *
     * <code>optional string ad_slot_code = 10;</code>
     * @return The bytes for adSlotCode.
     */
    com.google.protobuf.ByteString
        getAdSlotCodeBytes();

    /**
     * <pre>
     * 采样率-万分位
     * </pre>
     *
     * <code>optional int32 sampling_rate = 6;</code>
     * @return Whether the samplingRate field is set.
     */
    boolean hasSamplingRate();
    /**
     * <pre>
     * 采样率-万分位
     * </pre>
     *
     * <code>optional int32 sampling_rate = 6;</code>
     * @return The samplingRate.
     */
    int getSamplingRate();

    /**
     * <pre>
     * 启用/禁用状态,0-禁用,1-启用
     * </pre>
     *
     * <code>optional int32 status = 9;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <pre>
     * 启用/禁用状态,0-禁用,1-启用
     * </pre>
     *
     * <code>optional int32 status = 9;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code top.openadexchange.oax.model.proto.LogSamplingConfig}
   */
  public static final class LogSamplingConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.openadexchange.oax.model.proto.LogSamplingConfig)
      LogSamplingConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogSamplingConfig.newBuilder() to construct.
    private LogSamplingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogSamplingConfig() {
      logType_ = 0;
      adSlotCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogSamplingConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.openadexchange.oax.model.proto.OaxModelsProto.internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.openadexchange.oax.model.proto.OaxModelsProto.internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig.class, top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <pre>
     * 主键ID
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 主键ID
     * </pre>
     *
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int LOG_TYPE_FIELD_NUMBER = 2;
    private int logType_ = 0;
    /**
     * <pre>
     * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
     * </pre>
     *
     * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
     * @return Whether the logType field is set.
     */
    @java.lang.Override public boolean hasLogType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
     * </pre>
     *
     * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
     * @return The logType.
     */
    @java.lang.Override public top.openadexchange.oax.model.proto.OaxModelsProto.LogType getLogType() {
      top.openadexchange.oax.model.proto.OaxModelsProto.LogType result = top.openadexchange.oax.model.proto.OaxModelsProto.LogType.forNumber(logType_);
      return result == null ? top.openadexchange.oax.model.proto.OaxModelsProto.LogType.GLOBAL : result;
    }

    public static final int MEDIA_ID_FIELD_NUMBER = 3;
    private int mediaId_ = 0;
    /**
     * <pre>
     * 媒体ID
     * </pre>
     *
     * <code>optional int32 media_id = 3;</code>
     * @return Whether the mediaId field is set.
     */
    @java.lang.Override
    public boolean hasMediaId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 媒体ID
     * </pre>
     *
     * <code>optional int32 media_id = 3;</code>
     * @return The mediaId.
     */
    @java.lang.Override
    public int getMediaId() {
      return mediaId_;
    }

    public static final int DSP_ID_FIELD_NUMBER = 4;
    private int dspId_ = 0;
    /**
     * <pre>
     * DSP平台ID
     * </pre>
     *
     * <code>optional int32 dsp_id = 4;</code>
     * @return Whether the dspId field is set.
     */
    @java.lang.Override
    public boolean hasDspId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * DSP平台ID
     * </pre>
     *
     * <code>optional int32 dsp_id = 4;</code>
     * @return The dspId.
     */
    @java.lang.Override
    public int getDspId() {
      return dspId_;
    }

    public static final int AD_SLOT_ID_FIELD_NUMBER = 5;
    private int adSlotId_ = 0;
    /**
     * <pre>
     * 媒体广告位ID
     * </pre>
     *
     * <code>optional int32 ad_slot_id = 5;</code>
     * @return Whether the adSlotId field is set.
     */
    @java.lang.Override
    public boolean hasAdSlotId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 媒体广告位ID
     * </pre>
     *
     * <code>optional int32 ad_slot_id = 5;</code>
     * @return The adSlotId.
     */
    @java.lang.Override
    public int getAdSlotId() {
      return adSlotId_;
    }

    public static final int AD_SLOT_CODE_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object adSlotCode_ = "";
    /**
     * <pre>
     *媒体广告位编码
     * </pre>
     *
     * <code>optional string ad_slot_code = 10;</code>
     * @return Whether the adSlotCode field is set.
     */
    @java.lang.Override
    public boolean hasAdSlotCode() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *媒体广告位编码
     * </pre>
     *
     * <code>optional string ad_slot_code = 10;</code>
     * @return The adSlotCode.
     */
    @java.lang.Override
    public java.lang.String getAdSlotCode() {
      java.lang.Object ref = adSlotCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adSlotCode_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *媒体广告位编码
     * </pre>
     *
     * <code>optional string ad_slot_code = 10;</code>
     * @return The bytes for adSlotCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdSlotCodeBytes() {
      java.lang.Object ref = adSlotCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adSlotCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SAMPLING_RATE_FIELD_NUMBER = 6;
    private int samplingRate_ = 0;
    /**
     * <pre>
     * 采样率-万分位
     * </pre>
     *
     * <code>optional int32 sampling_rate = 6;</code>
     * @return Whether the samplingRate field is set.
     */
    @java.lang.Override
    public boolean hasSamplingRate() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 采样率-万分位
     * </pre>
     *
     * <code>optional int32 sampling_rate = 6;</code>
     * @return The samplingRate.
     */
    @java.lang.Override
    public int getSamplingRate() {
      return samplingRate_;
    }

    public static final int STATUS_FIELD_NUMBER = 9;
    private int status_ = 0;
    /**
     * <pre>
     * 启用/禁用状态,0-禁用,1-启用
     * </pre>
     *
     * <code>optional int32 status = 9;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 启用/禁用状态,0-禁用,1-启用
     * </pre>
     *
     * <code>optional int32 status = 9;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, logType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, mediaId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, dspId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, adSlotId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(6, samplingRate_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt32(9, status_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, adSlotCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, logType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, mediaId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dspId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, adSlotId_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, samplingRate_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, status_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, adSlotCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig)) {
        return super.equals(obj);
      }
      top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig other = (top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasLogType() != other.hasLogType()) return false;
      if (hasLogType()) {
        if (logType_ != other.logType_) return false;
      }
      if (hasMediaId() != other.hasMediaId()) return false;
      if (hasMediaId()) {
        if (getMediaId()
            != other.getMediaId()) return false;
      }
      if (hasDspId() != other.hasDspId()) return false;
      if (hasDspId()) {
        if (getDspId()
            != other.getDspId()) return false;
      }
      if (hasAdSlotId() != other.hasAdSlotId()) return false;
      if (hasAdSlotId()) {
        if (getAdSlotId()
            != other.getAdSlotId()) return false;
      }
      if (hasAdSlotCode() != other.hasAdSlotCode()) return false;
      if (hasAdSlotCode()) {
        if (!getAdSlotCode()
            .equals(other.getAdSlotCode())) return false;
      }
      if (hasSamplingRate() != other.hasSamplingRate()) return false;
      if (hasSamplingRate()) {
        if (getSamplingRate()
            != other.getSamplingRate()) return false;
      }
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (getStatus()
            != other.getStatus()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasLogType()) {
        hash = (37 * hash) + LOG_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + logType_;
      }
      if (hasMediaId()) {
        hash = (37 * hash) + MEDIA_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMediaId();
      }
      if (hasDspId()) {
        hash = (37 * hash) + DSP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getDspId();
      }
      if (hasAdSlotId()) {
        hash = (37 * hash) + AD_SLOT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getAdSlotId();
      }
      if (hasAdSlotCode()) {
        hash = (37 * hash) + AD_SLOT_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getAdSlotCode().hashCode();
      }
      if (hasSamplingRate()) {
        hash = (37 * hash) + SAMPLING_RATE_FIELD_NUMBER;
        hash = (53 * hash) + getSamplingRate();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.openadexchange.oax.model.proto.LogSamplingConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.openadexchange.oax.model.proto.LogSamplingConfig)
        top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.openadexchange.oax.model.proto.OaxModelsProto.internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.openadexchange.oax.model.proto.OaxModelsProto.internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig.class, top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig.Builder.class);
      }

      // Construct using top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        logType_ = 0;
        mediaId_ = 0;
        dspId_ = 0;
        adSlotId_ = 0;
        adSlotCode_ = "";
        samplingRate_ = 0;
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.openadexchange.oax.model.proto.OaxModelsProto.internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_descriptor;
      }

      @java.lang.Override
      public top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig getDefaultInstanceForType() {
        return top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig.getDefaultInstance();
      }

      @java.lang.Override
      public top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig build() {
        top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig buildPartial() {
        top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig result = new top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.logType_ = logType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mediaId_ = mediaId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.dspId_ = dspId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.adSlotId_ = adSlotId_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.adSlotCode_ = adSlotCode_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.samplingRate_ = samplingRate_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig) {
          return mergeFrom((top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig other) {
        if (other == top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLogType()) {
          setLogType(other.getLogType());
        }
        if (other.hasMediaId()) {
          setMediaId(other.getMediaId());
        }
        if (other.hasDspId()) {
          setDspId(other.getDspId());
        }
        if (other.hasAdSlotId()) {
          setAdSlotId(other.getAdSlotId());
        }
        if (other.hasAdSlotCode()) {
          adSlotCode_ = other.adSlotCode_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasSamplingRate()) {
          setSamplingRate(other.getSamplingRate());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                int tmpRaw = input.readEnum();
                top.openadexchange.oax.model.proto.OaxModelsProto.LogType tmpValue =
                    top.openadexchange.oax.model.proto.OaxModelsProto.LogType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  logType_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              case 24: {
                mediaId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                dspId_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                adSlotId_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                samplingRate_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 48
              case 72: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 72
              case 82: {
                adSlotCode_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * 主键ID
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 主键ID
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 主键ID
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 主键ID
       * </pre>
       *
       * <code>optional int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int logType_ = 0;
      /**
       * <pre>
       * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
       * </pre>
       *
       * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
       * @return Whether the logType field is set.
       */
      @java.lang.Override public boolean hasLogType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
       * </pre>
       *
       * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
       * @return The logType.
       */
      @java.lang.Override
      public top.openadexchange.oax.model.proto.OaxModelsProto.LogType getLogType() {
        top.openadexchange.oax.model.proto.OaxModelsProto.LogType result = top.openadexchange.oax.model.proto.OaxModelsProto.LogType.forNumber(logType_);
        return result == null ? top.openadexchange.oax.model.proto.OaxModelsProto.LogType.GLOBAL : result;
      }
      /**
       * <pre>
       * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
       * </pre>
       *
       * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
       * @param value The logType to set.
       * @return This builder for chaining.
       */
      public Builder setLogType(top.openadexchange.oax.model.proto.OaxModelsProto.LogType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        logType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 日志类型：GLOBAL,BID_REQ,BID_RSP,DSP_REQ,DSP_RSP
       * </pre>
       *
       * <code>optional .top.openadexchange.oax.model.proto.LogType log_type = 2 [default = GLOBAL];</code>
       * @return This builder for chaining.
       */
      public Builder clearLogType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logType_ = 0;
        onChanged();
        return this;
      }

      private int mediaId_ ;
      /**
       * <pre>
       * 媒体ID
       * </pre>
       *
       * <code>optional int32 media_id = 3;</code>
       * @return Whether the mediaId field is set.
       */
      @java.lang.Override
      public boolean hasMediaId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 媒体ID
       * </pre>
       *
       * <code>optional int32 media_id = 3;</code>
       * @return The mediaId.
       */
      @java.lang.Override
      public int getMediaId() {
        return mediaId_;
      }
      /**
       * <pre>
       * 媒体ID
       * </pre>
       *
       * <code>optional int32 media_id = 3;</code>
       * @param value The mediaId to set.
       * @return This builder for chaining.
       */
      public Builder setMediaId(int value) {

        mediaId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 媒体ID
       * </pre>
       *
       * <code>optional int32 media_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mediaId_ = 0;
        onChanged();
        return this;
      }

      private int dspId_ ;
      /**
       * <pre>
       * DSP平台ID
       * </pre>
       *
       * <code>optional int32 dsp_id = 4;</code>
       * @return Whether the dspId field is set.
       */
      @java.lang.Override
      public boolean hasDspId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * DSP平台ID
       * </pre>
       *
       * <code>optional int32 dsp_id = 4;</code>
       * @return The dspId.
       */
      @java.lang.Override
      public int getDspId() {
        return dspId_;
      }
      /**
       * <pre>
       * DSP平台ID
       * </pre>
       *
       * <code>optional int32 dsp_id = 4;</code>
       * @param value The dspId to set.
       * @return This builder for chaining.
       */
      public Builder setDspId(int value) {

        dspId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * DSP平台ID
       * </pre>
       *
       * <code>optional int32 dsp_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDspId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dspId_ = 0;
        onChanged();
        return this;
      }

      private int adSlotId_ ;
      /**
       * <pre>
       * 媒体广告位ID
       * </pre>
       *
       * <code>optional int32 ad_slot_id = 5;</code>
       * @return Whether the adSlotId field is set.
       */
      @java.lang.Override
      public boolean hasAdSlotId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 媒体广告位ID
       * </pre>
       *
       * <code>optional int32 ad_slot_id = 5;</code>
       * @return The adSlotId.
       */
      @java.lang.Override
      public int getAdSlotId() {
        return adSlotId_;
      }
      /**
       * <pre>
       * 媒体广告位ID
       * </pre>
       *
       * <code>optional int32 ad_slot_id = 5;</code>
       * @param value The adSlotId to set.
       * @return This builder for chaining.
       */
      public Builder setAdSlotId(int value) {

        adSlotId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 媒体广告位ID
       * </pre>
       *
       * <code>optional int32 ad_slot_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdSlotId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        adSlotId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object adSlotCode_ = "";
      /**
       * <pre>
       *媒体广告位编码
       * </pre>
       *
       * <code>optional string ad_slot_code = 10;</code>
       * @return Whether the adSlotCode field is set.
       */
      public boolean hasAdSlotCode() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *媒体广告位编码
       * </pre>
       *
       * <code>optional string ad_slot_code = 10;</code>
       * @return The adSlotCode.
       */
      public java.lang.String getAdSlotCode() {
        java.lang.Object ref = adSlotCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            adSlotCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *媒体广告位编码
       * </pre>
       *
       * <code>optional string ad_slot_code = 10;</code>
       * @return The bytes for adSlotCode.
       */
      public com.google.protobuf.ByteString
          getAdSlotCodeBytes() {
        java.lang.Object ref = adSlotCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adSlotCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *媒体广告位编码
       * </pre>
       *
       * <code>optional string ad_slot_code = 10;</code>
       * @param value The adSlotCode to set.
       * @return This builder for chaining.
       */
      public Builder setAdSlotCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        adSlotCode_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *媒体广告位编码
       * </pre>
       *
       * <code>optional string ad_slot_code = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdSlotCode() {
        adSlotCode_ = getDefaultInstance().getAdSlotCode();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *媒体广告位编码
       * </pre>
       *
       * <code>optional string ad_slot_code = 10;</code>
       * @param value The bytes for adSlotCode to set.
       * @return This builder for chaining.
       */
      public Builder setAdSlotCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        adSlotCode_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private int samplingRate_ ;
      /**
       * <pre>
       * 采样率-万分位
       * </pre>
       *
       * <code>optional int32 sampling_rate = 6;</code>
       * @return Whether the samplingRate field is set.
       */
      @java.lang.Override
      public boolean hasSamplingRate() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * 采样率-万分位
       * </pre>
       *
       * <code>optional int32 sampling_rate = 6;</code>
       * @return The samplingRate.
       */
      @java.lang.Override
      public int getSamplingRate() {
        return samplingRate_;
      }
      /**
       * <pre>
       * 采样率-万分位
       * </pre>
       *
       * <code>optional int32 sampling_rate = 6;</code>
       * @param value The samplingRate to set.
       * @return This builder for chaining.
       */
      public Builder setSamplingRate(int value) {

        samplingRate_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 采样率-万分位
       * </pre>
       *
       * <code>optional int32 sampling_rate = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSamplingRate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        samplingRate_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 启用/禁用状态,0-禁用,1-启用
       * </pre>
       *
       * <code>optional int32 status = 9;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * 启用/禁用状态,0-禁用,1-启用
       * </pre>
       *
       * <code>optional int32 status = 9;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 启用/禁用状态,0-禁用,1-启用
       * </pre>
       *
       * <code>optional int32 status = 9;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 启用/禁用状态,0-禁用,1-启用
       * </pre>
       *
       * <code>optional int32 status = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000080);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.openadexchange.oax.model.proto.LogSamplingConfig)
    }

    // @@protoc_insertion_point(class_scope:top.openadexchange.oax.model.proto.LogSamplingConfig)
    private static final top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig();
    }

    public static top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LogSamplingConfig>
        PARSER = new com.google.protobuf.AbstractParser<LogSamplingConfig>() {
      @java.lang.Override
      public LogSamplingConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LogSamplingConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogSamplingConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.openadexchange.oax.model.proto.OaxModelsProto.LogSamplingConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020oax-models.proto\022\"top.openadexchange.o" +
      "ax.model.proto\"\331\001\n\021LogSamplingConfig\022\n\n\002" +
      "id\030\001 \001(\003\022E\n\010log_type\030\002 \001(\0162+.top.openade" +
      "xchange.oax.model.proto.LogType:\006GLOBAL\022" +
      "\020\n\010media_id\030\003 \001(\005\022\016\n\006dsp_id\030\004 \001(\005\022\022\n\nad_" +
      "slot_id\030\005 \001(\005\022\024\n\014ad_slot_code\030\n \001(\t\022\025\n\rs" +
      "ampling_rate\030\006 \001(\005\022\016\n\006status\030\t \001(\005*I\n\007Lo" +
      "gType\022\n\n\006GLOBAL\020\000\022\013\n\007BID_REQ\020\001\022\013\n\007BID_RS" +
      "P\020\002\022\013\n\007DSP_REQ\020\003\022\013\n\007DSP_RSP\020\004B4\n\"top.ope" +
      "nadexchange.oax.model.protoB\016OaxModelsPr" +
      "oto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_openadexchange_oax_model_proto_LogSamplingConfig_descriptor,
        new java.lang.String[] { "Id", "LogType", "MediaId", "DspId", "AdSlotId", "AdSlotCode", "SamplingRate", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
