debug=false
spring.datasource.url=jdbc:mysql://10.10.2.10:3306/open_adexchange?allowPublicKeyRetrieval=true&remarks=true\
  &useInformationSchema=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&tinyInt1isBit=true
spring.datasource.username=ENC(m/f4UPEbLzh+pkJG5FEH9g==)
spring.datasource.password=ENC(ocFHCYjxZw92OOPKMS0TmeVuYTIx6NlG)
#redis config
spring.data.redis.host=10.10.2.13
spring.data.redis.port=6379
spring.data.redis.password=ENC(UmVVUpkaX7oEKtPpxxEhafnIT0a0vQsZ)
openadexchange.tencent.cos.secretId=ENC(NYyg5V+Y5vCW0idFYSESB00KYMBEIVpgjOSFUA0X6xOZ8d2zToAkiV2Wv7xosbne)
openadexchange.tencent.cos.secretKey=ENC(XTDMFAExTbMZxGntlHUwyaFA0WrDmvHRZQeQFVmbrXHaEIrT9k0QBXDRGhrumTPS)
openadexchange.tencent.cos.region=ap-beijing
openadexchange.tencent.cos.bucket=open-adexchange-1301501150
openadexchange.tencent.cos.domain=open-adexchange-1301501150.cos.ap-beijing.myqcloud.com
openadexchange.tencent.cos.https=true
openadexchange.tencent.cos.enable=true

spring.kafka.bootstrap-servers=10.10.2.14:9092

#spring.kafka.consumer.group-id=adx-consumer-group
#spring.kafka.consumer.enable-auto-commit=true
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.listener.ack-mode=manual
#spring.kafka.listener.concurrency=8

oax.engine.dsp-call-timeout=100000
#跟踪服务器URL，用于生成ADX平台自有的曝光和点击监测地址
#例如: http://your-tracking-server.com 或 https://your-tracking-server.com
oax.engine.tracking-url=http://49.233.107.105/track
oax.tracking.secret=ENC(Jx1p7cYEgze3nYCzGf0SRKEEsoJ5MNue)