package top.openadexchange.constants.enums;

public enum DomainEventType {
    DSP_CREATED,
    DSP_UPDATED,
    DSP_DELETED,
    PUBLISHER_CREATED,
    PUBLISHER_UPDATED,
    PUBLISHER_DELETED,
    SITE_CREATED,
    SITE_UPDATED,
    SITE_DELETED,
    SITE_AD_PLACEMENT_CREATED,
    SITE_AD_PLACEMENT_UPDATED,
    SITE_AD_PLACEMENT_DELETED,
    AD_PLACEMENT_CREATED,
    AD_PLACEMENT_UPDATED,
    AD_PLACEMENT_DELETED,
    LOG_SAMPLING_CONFIG_CREATED,
    LOG_SAMPLING_CONFIG_UPDATED,
    LOG_SAMPLING_CONFIG_DELETED
}
