spring.data.redis.host=10.10.2.13
spring.data.redis.port=6379
spring.data.redis.password=ENC(7XkIIXBTf/kUNfUk6OjxnPcwFddjgEsK)
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.time-between-eviction-runs=30s
#kafka相关配置
spring.kafka.bootstrap-servers=10.10.2.14:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# 追踪相关配置
oax.tracking.executor-factory=default
oax.tracking.ad-dedup-service=default
oax.tracking.secret=ENC(Jx1p7cYEgze3nYCzGf0SRKEEsoJ5MNue)