spring.data.redis.host=101.126.128.177
spring.data.redis.port=8379
spring.data.redis.password=ENC(3P1JCE9zgqWSqq5I0OaENusyd4Ux6zvc2vN/iY8RH6o=)
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.time-between-eviction-runs=30s

#kafka相关配置
spring.kafka.bootstrap-servers=127.0.0.1:9092